# Generated by Django 2.2.24 on 2022-03-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название организации/страны/человека', max_length=200, verbose_name='Имя')),
                ('link', models.TextField(help_text='Вставьте ссылку, куда будут происходить денежные переводы', verbose_name='Ссылка')),
                ('Decryption', models.TextField(help_text='Введите описание того,  на что пойдут пожертвования', verbose_name='Описание')),
                ('Picture', models.ImageField(help_text='Вставьте картинку, относящуюся к пожертвованиям', upload_to='', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите статус пожертвований', max_length=30, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип пожертвований', max_length=200, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Org')),
                ('status', models.ForeignKey(help_text='Изменить статус пожертвований', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Status', verbose_name='Статус пожертвований')),
            ],
        ),
    ]
