# Generated by Django 2.2.24 on 2022-03-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='TypeOrg',
            field=models.ForeignKey(help_text='Выберите тип пожертвований', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Type', verbose_name='Тип пожертвований'),
        ),
    ]
