# Generated by Django 2.2.24 on 2022-03-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_org_typeorg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='Lub',
            new_name='org',
        ),
    ]
