# Generated by Django 2.2.24 on 2022-03-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_orgform'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='Summa',
            field=models.CharField(help_text='Введите количество сборов в рублях', max_length=50, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='org',
            name='Decryption',
            field=models.CharField(help_text='Введите описание того,  на что пойдут пожертвования', max_length=220, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='org',
            name='Picture',
            field=models.ImageField(help_text='Вставьте картинку, относящуюся к пожертвованиям', upload_to='images/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(help_text='Введите название организации/страны/человека', max_length=40, verbose_name='Имя'),
        ),
    ]
