# Generated by Django 2.2.24 on 2022-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220320_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.TextField(help_text='Вставьте ссылку, куда будут происходить денежные переводы', verbose_name='Ссылка')),
                ('Name', models.CharField(help_text='Введите ваши контактные данные', max_length=200, verbose_name='Имя')),
            ],
        ),
    ]
