# Generated by Django 2.2.24 on 2022-03-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_help'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='Link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='help',
            old_name='Name',
            new_name='name',
        ),
    ]
